
SUPABASE_URL = "https://xaqttbolcbhfrsrvoghi.supabase.co"
SUPABASE_KEY = "sb_publishable_wMn2pnZiekIMxFTtkv7Npw_kGvHU74R"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhcXR0Ym9sY2JoZnJzcnZvZ2hpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTI2MzU3MiwiZXhwIjoyMDk2ODM5NTcyfQ.lyOjd5CEVmOyw0-JiVNl9nhItSTHLMcN0bAdh5ap634"
[mpesa]
consumer_key = "WGXsTlKQRuwKer0nb2eGGarv6eWMGQUl7m42eKCTjPPoHvN3"
consumer_secret = "TNnVKAvuZu64zMc7vVgfhdGJ5G6uYA6BPcJXvzgg5uu38kkYKQTmXS9y2yJjQBE1"



